In [1]:
import pandas as pd
import numpy as np

In [4]:
x=np.random.randint(6,30,9).reshape(3,3)
x

array([[ 7, 19, 26],
       [25, 28, 13],
       [16, 29, 13]])

In [3]:
sum(x)

135

In [6]:
np.sum(x,axis=1)

array([52, 66, 58])

In [7]:
np.sum(x,axis=0)

array([48, 76, 52])

In [20]:
z=np.random.randint(18,76,25)
z

array([40, 31, 25, 19, 57, 25, 62, 24, 41, 37, 47, 57, 46, 47, 71, 56, 42,
       56, 62, 75, 37, 55, 65, 30, 48])

In [21]:
a=z[z%2==1]
a

array([31, 25, 19, 57, 25, 41, 37, 47, 57, 47, 71, 75, 37, 55, 65])

array([35, 67, 31, 49, 59, -1, 27, -1, 43, 65, 61, -1, 49, 43, -1, 33, -1,
       -1, -1, -1, 23, 75, -1, 23, -1])

In [86]:
z=np.random.randint(18,76,21).reshape(3,7)
z

array([[35, 35, 42, 39, 70, 67, 46],
       [42, 40, 60, 21, 23, 21, 45],
       [66, 55, 37, 28, 22, 66, 31]])

In [97]:
z=np.random.randint(45,90,25)
z

array([61, 71, 75, 89, 51, 61, 46, 81, 51, 80, 72, 67, 70, 72, 64, 65, 85,
       50, 85, 61, 80, 57, 66, 81, 83])

In [98]:
b=np.copy(z)
b

array([61, 71, 75, 89, 51, 61, 46, 81, 51, 80, 72, 67, 70, 72, 64, 65, 85,
       50, 85, 61, 80, 57, 66, 81, 83])

In [99]:
a=(z%2==0)
z[a]=-3

In [100]:
z

array([61, 71, 75, 89, 51, 61, -3, 81, 51, -3, -3, 67, -3, -3, -3, 65, 85,
       -3, 85, 61, -3, 57, -3, 81, 83])

In [101]:
b

array([61, 71, 75, 89, 51, 61, 46, 81, 51, 80, 72, 67, 70, 72, 64, 65, 85,
       50, 85, 61, 80, 57, 66, 81, 83])

In [84]:
z

array([-3, -3, -3, 87, -3, -3, 55, 67, -3, 83, -3, -3, -3, 81, 47, 85, 61,
       57, 67, -3, -3, 73, -3, -3, 69])

In [102]:
import numpy as np
d=np.array([10,20,30,40,50,60,70])
print(d[-4:])

[40 50 60 70]


In [106]:
import numpy as np
a1=np.array([10,12,14,16,18,20,22])
a2=np.array([10,12,15,16,12,20,12])
a=(np.where(a1==a2))
print(a1[a])

[10 12 16 20]


In [107]:
list=[1,0,0,0,1,0,0,0,1]
list

[1, 0, 0, 0, 1, 0, 0, 0, 1]

In [109]:
a=np.array(list).reshape(3,3)
a

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [111]:
b=np.random.randint(10,20,6)
b

array([13, 11, 14, 18, 17, 15])

In [138]:
a[a==0]=b

ValueError: NumPy boolean array indexing assignment cannot assign 6 input values to the 0 output values where the mask is true

In [139]:
a

array([[ 1, 13, 11],
       [14,  1, 18],
       [17, 15,  1]])

In [132]:
m=np.array([13,0,0,25])
n=np.array([20,30])

In [134]:
m[m==0]

array([0, 0])

In [135]:
m[m==0]=n

m

In [136]:
m

array([13, 20, 30, 25])

In [148]:
list=[0,1,1,1,0,1,1,1,0]
list

[0, 1, 1, 1, 0, 1, 1, 1, 0]

In [149]:
a=np.array(list).reshape(3,3)
a

array([[0, 1, 1],
       [1, 0, 1],
       [1, 1, 0]])

In [152]:
b=np.random.randint(1,10,3)
b

array([9, 5, 3])

In [153]:
a[a==0]=b

In [197]:
a

array([[2, 4, 6]])

In [198]:
l=[2,4,6,7,8,9,1,2,3]
l


[2, 4, 6, 7, 8, 9, 1, 2, 3]

In [205]:
a=np.array(l).reshape(3,3)
a

array([[2, 4, 6],
       [7, 8, 9],
       [1, 2, 3]])

In [206]:
x=np.vsplit(a,3)[0]
x

array([[2, 4, 6]])

In [217]:
b=np.hsplit(a,3)[1].T
b

array([[4, 8, 2]])

In [218]:
np.hstack([x,b])

array([[2, 4, 6, 4, 8, 2]])

In [221]:
np.concatenate([x,b])


array([[2, 4, 6],
       [4, 8, 2]])