In [1]:
import numpy as np

In [2]:
l1 = [10, 20, 30, 40, 50]
l1

[10, 20, 30, 40, 50]

In [3]:
l2 = [100, 200, 300, 400, 500]
l2

[100, 200, 300, 400, 500]

In [7]:
l1 + l2

[10, 20, 30, 40, 50, 100, 200, 300, 400, 500]

In [4]:
arr1 = np.array(l1)
arr1

array([10, 20, 30, 40, 50])

In [6]:
arr2 = np.array(l2)
arr2

array([100, 200, 300, 400, 500])

In [8]:

arr1 + arr2 

array([110, 220, 330, 440, 550])

In [9]:
l2 - l1

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [10]:
arr2 - arr1

array([ 90, 180, 270, 360, 450])

In [11]:
arr1 * 4

array([ 40,  80, 120, 160, 200])

In [13]:
arr2 / 10

array([10., 20., 30., 40., 50.])

In [14]:
arr3 = np.array([25, 50, 75])
arr3

array([25, 50, 75])

In [15]:
arr1

array([10, 20, 30, 40, 50])

In [16]:
arr1 + arr3

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

In [17]:
np.mean(arr1)

30.0

In [18]:
np.median(arr1)

30.0

In [ ]:
57, 85, 42, 27, 18, 59, 96

In [ ]:
18, 27, 42, 57, 59, 85  => 42 + 57/ 2 =>49.5

In [19]:
np.mode(arr1)

AttributeError: module 'numpy' has no attribute 'mode'

In [20]:
np.count(arr1)

AttributeError: module 'numpy' has no attribute 'count'

In [21]:
arr = np.random.randint(25, 75, 12)
arr

array([55, 50, 35, 46, 55, 38, 69, 57, 50, 73, 31, 40])

In [22]:
# Get all the values from arr greater than 50

arr>50

array([ True, False, False, False,  True, False,  True,  True, False,
        True, False, False])

In [23]:
arr[arr>50]

array([55, 55, 69, 57, 73])

In [24]:
arr[2]

35

In [26]:
# Get all the values greater than 40 and lesss than 60 from the arr
# arr > 40  & arr < 60

arr[(arr > 40) & (arr < 60)]

array([55, 50, 46, 55, 57, 50])

In [28]:
# Get all the values divisible by 3 & 5 from the arr

arr[(arr % 3 == 0) & (arr % 5 == 0)]

array([], dtype=int32)

In [29]:
arr

array([55, 50, 35, 46, 55, 38, 69, 57, 50, 73, 31, 40])

In [30]:
arr_reshaped = np.reshape(arr, (3,4))
arr_reshaped

array([[55, 50, 35, 46],
       [55, 38, 69, 57],
       [50, 73, 31, 40]])

In [32]:
arr_resized = np.resize(arr, (3, 4))
arr_resized

array([[55, 50, 35, 46],
       [55, 38, 69, 57],
       [50, 73, 31, 40]])

In [39]:
arr_reshaped[1,2] = 708
arr_reshaped

array([[ 55,  50,  35,  46],
       [ 55,  38, 708,  57],
       [ 50,  73,  31,  40]])

In [40]:
arr

array([ 55,  50,  35,  46,  55,  38, 708,  57,  50,  73,  31,  40])

In [41]:
arr_resized[2,2] = 777
arr_resized

array([[ 55,  50,  35,  46],
       [ 55,  38,  69,  57],
       [ 50,  73, 777,  40]])

In [42]:
arr

array([ 55,  50,  35,  46,  55,  38, 708,  57,  50,  73,  31,  40])

In [44]:
arr_resized

array([[ 55,  50,  35,  46],
       [ 55,  38,  69,  57],
       [ 50,  73, 777,  40]])

In [45]:
np.sum(arr_resized)

1345

In [46]:
np.sum(arr_resized, axis = 0)

array([160, 161, 881, 143])

In [47]:
np.sum(arr_resized, axis = 1)

array([186, 219, 940])

In [48]:
arr_resized

array([[ 55,  50,  35,  46],
       [ 55,  38,  69,  57],
       [ 50,  73, 777,  40]])

In [50]:
arr_flattened = arr_resized.flatten()
arr_flattened

array([ 55,  50,  35,  46,  55,  38,  69,  57,  50,  73, 777,  40])

In [51]:
arr_raveled = np.ravel(arr_resized)
arr_raveled

array([ 55,  50,  35,  46,  55,  38,  69,  57,  50,  73, 777,  40])