In [1]:
import pandas as pd
import numpy as np

Q1. Write a NumPy program to print the NumPy version on your system.  

Q2. Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array 
.
Expected Outpu    t:
Original List: [12.23, 13.32, 100, 36.   32]
One-dimensional NumPy array: array([ 12.23 13.32 100. 36.      
32])
Q3. Write a NumPy program to convert an array to a floating   type.
Sample output:
Original array
[1, 2, 3, 4]
Array converted to a float type:
[ 1. 2. 3. 4.]

        Q4. Write a NumPy program to create a null vector of size 10 and update the sixth value to 11.
[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]
Q5. Write a NumPy program to create an array with values ranging from 12 to 38.
Expected Output:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]

Q.6. An ndarray X contains the following data:
[[0 1 2 3]
[4 5 6 7]
[8 9 10 11]
[12 13 14 15]]
What will be returned by the statements:
i) print(X[0:2,0:2]
ii) print(X[2:0,2:0]
iii) print(X[2:0:-1,2:0:-1])
Q.7. Given the following ndarray Ary1 [[1 2 3],
[4 5 6],
[7 8 9]]
Write array slices to print:
a) Hoizontal rows separately
b) Veritcal columns separately
Q.8. Consider the two arrays: ar1=[[0 1 2],
[3 4 5],
[6 7 8]]
ar2=[[10 11 12]
[13 14 15]
[16 17 18]]
i) Write command to concatenate ar1 and ar2- i) rowwise and ii) columnwise
ii) What be the resultant array if the follwing statement is given?
np.hstack([ar1,ar2])
Q.9. Given a list L=[3,4,5] and an nd

In [4]:
x=[[1 ,2, 3],
   [4 ,5 ,6],
   [7, 8 ,9]]
print(x)


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [9]:
print(x[0:1])

[[1, 2, 3]]


In [11]:
print(x[1:2])

[[4, 5, 6]]


In [12]:
print(x[2:3])

[[7, 8, 9]]


In [19]:
print(x[: ,1])

TypeError: list indices must be integers or slices, not tuple

In [20]:
print(x)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [26]:
type(x)

list

In [27]:
import numpy as np
l1=np.array(x)
l1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
np.split(l1,3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [39]:
np.hsplit(l1,3)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

### 

In [41]:
ar1=[[0,1,2],
     [3,4,5],
     [6,7,8]]
print(ar1)

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]


In [43]:
x1=np.array(ar1)
x1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [44]:
ar2=[[10,11,12],
     [13,14,15],
     [16,17,18]]
ar2

[[10, 11, 12], [13, 14, 15], [16, 17, 18]]

In [45]:
x2=np.array(ar2)
x2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [46]:
x3=x1+x2
x3

array([[10, 12, 14],
       [16, 18, 20],
       [22, 24, 26]])

In [50]:
print(np.sum(x1,axis=0))

[ 9 12 15]


In [52]:
print(np.sum(x1,axis=1))

[ 3 12 21]


In [55]:
np.hstack([x1,x2])

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15],
       [ 6,  7,  8, 16, 17, 18]])

In [56]:
l=[3,4,5]
l*3

[3, 4, 5, 3, 4, 5, 3, 4, 5]

In [57]:
n=[3,4,5]
n*3

[3, 4, 5, 3, 4, 5, 3, 4, 5]

In [58]:
l+l

[3, 4, 5, 3, 4, 5]

In [59]:
n+n

[3, 4, 5, 3, 4, 5]

In [60]:
l1=np.array(n)
l1

array([3, 4, 5])

In [61]:
l1*3

array([ 9, 12, 15])

In [62]:
l1+l1

array([ 6,  8, 10])

In [69]:

import numpy as np
x=np.zeros(6)
print(x)
x[2]=15
x[4]=25
print(x)


[0. 0. 0. 0. 0. 0.]
[ 0.  0. 15.  0. 25.  0.]


In [70]:
a=[10,20,30,40,50,60,70,80,90]
a

[10, 20, 30, 40, 50, 60, 70, 80, 90]

In [72]:
b=[[0,1,2,3],
   [4,5,6,7],
   [8,9,10,11],
   [12,13,14,15]]
b

[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]]

In [75]:
B=np.array(b)
B

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [76]:
B[0:2,1:3]

array([[1, 2],
       [5, 6]])

In [77]:
A=np.array(a)
A

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [78]:
A[2:6:3]

array([30, 60])

In [79]:
A[-1:-3]

array([], dtype=int32)

In [80]:
B[::-1]

array([[12, 13, 14, 15],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

In [81]:
B[:3,2]

array([ 2,  6, 10])

In [82]:
x=np.array([1,2,3])
y=np.array([3,2,1])
z=np.concatenate([x,y])
print(z)

[1 2 3 3 2 1]


In [83]:
grid=np.array([[1,2,3],[4,5,6]])
g2=np.concatenate([grid,grid])
print(g2)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [84]:
grid=np.array([[1,2,3],[4,5,6]])
g2=np.concatenate([grid,grid],axis=1)
print(g2)

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [88]:
x=np.array([1,2,3])
g=np.array([[9,8,7],[6,5,4]])
r=np.vstack([x,g])
print(r)

[[1 2 3]
 [9 8 7]
 [6 5 4]]


In [90]:
g=np.array([[9,8,7],[6,5,4]])
y=np.array([[99],[99]])
r=np.hstack([g,y])
print(r)


[[ 9  8  7 99]
 [ 6  5  4 99]]


In [93]:
p=np.random.randint(11,71,16).reshape(4,4)
p

array([[16, 32, 11, 48],
       [22, 36, 65, 58],
       [27, 64, 55, 32],
       [29, 67, 40, 32]])

In [94]:
q=np.random.randint(2,41,16).reshape(4,4)
q

array([[19, 12,  4,  5],
       [ 7, 28, 16, 19],
       [33, 39, 37, 35],
       [16, 23, 32, 23]])

In [95]:
p=p+10
p

array([[26, 42, 21, 58],
       [32, 46, 75, 68],
       [37, 74, 65, 42],
       [39, 77, 50, 42]])

In [96]:
r=p*q
r

array([[ 494,  504,   84,  290],
       [ 224, 1288, 1200, 1292],
       [1221, 2886, 2405, 1470],
       [ 624, 1771, 1600,  966]])

In [98]:
y=q/7
y

array([[2.71428571, 1.71428571, 0.57142857, 0.71428571],
       [1.        , 4.        , 2.28571429, 2.71428571],
       [4.71428571, 5.57142857, 5.28571429, 5.        ],
       [2.28571429, 3.28571429, 4.57142857, 3.28571429]])

In [99]:
x=p%7
x

array([[5, 0, 0, 2],
       [4, 4, 5, 5],
       [2, 4, 2, 0],
       [4, 0, 1, 0]], dtype=int32)

In [103]:
A=np.arange(0,16).reshape(4,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [111]:
x=np.ones((10,10))
x[1:-1,1:-1]=0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
