In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
# Creating a dataset

data = pd.DataFrame({
    "Age" : [25, 28, 32, 36, 22, 40, 57, 37, 55, 58],
    "Salary" : [35000, 95000, 75000, 25000, 42000, 75000, 92000, 98000, 88000, 94000]
}
                   )
data

Age  Salary
0   25   35000
1   28   95000
2   32   75000
3   36   25000
4   22   42000
5   40   75000
6   57   92000
7   37   98000
8   55   88000
9   58   94000

In [4]:
from sklearn.model_selection import train_test_split
train, test = train_test_split(data, test_size = 0.3)

In [5]:
train

Age  Salary
8   55   88000
4   22   42000
6   57   92000
1   28   95000
9   58   94000
0   25   35000
3   36   25000

In [6]:
test

Age  Salary
7   37   98000
2   32   75000
5   40   75000

In [7]:
# K Fold cross validation

from sklearn.model_selection import KFold
kf = KFold(n_splits = 5)
kf

KFold(n_splits=5, random_state=None, shuffle=False)

In [8]:
kf.split(data)

<generator object _BaseKFold.split at 0x000001F8ED37A200>

In [9]:
list(kf.split(data))

[(array([2, 3, 4, 5, 6, 7, 8, 9]), array([0, 1])),
 (array([0, 1, 4, 5, 6, 7, 8, 9]), array([2, 3])),
 (array([0, 1, 2, 3, 6, 7, 8, 9]), array([4, 5])),
 (array([0, 1, 2, 3, 4, 5, 8, 9]), array([6, 7])),
 (array([0, 1, 2, 3, 4, 5, 6, 7]), array([8, 9]))]

In [10]:
# K Fold cross validation - for 10 sets of train and test set

from sklearn.model_selection import KFold
kf = KFold(n_splits = 10)
kf

KFold(n_splits=10, random_state=None, shuffle=False)

In [11]:
list(kf.split(data))

[(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([0])),
 (array([0, 2, 3, 4, 5, 6, 7, 8, 9]), array([1])),
 (array([0, 1, 3, 4, 5, 6, 7, 8, 9]), array([2])),
 (array([0, 1, 2, 4, 5, 6, 7, 8, 9]), array([3])),
 (array([0, 1, 2, 3, 5, 6, 7, 8, 9]), array([4])),
 (array([0, 1, 2, 3, 4, 6, 7, 8, 9]), array([5])),
 (array([0, 1, 2, 3, 4, 5, 7, 8, 9]), array([6])),
 (array([0, 1, 2, 3, 4, 5, 6, 8, 9]), array([7])),
 (array([0, 1, 2, 3, 4, 5, 6, 7, 9]), array([8])),
 (array([0, 1, 2, 3, 4, 5, 6, 7, 8]), array([9]))]